version: 0.2
phases:
  build:
    commands:
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name voting --kubeconfig ~/.kube/config

      - helm upgrade --install externaldns stable/external-dns --namespace externaldns --set rbac.create=true --set logLevel=debug --set image.tag=v0.5.12 --set txtOwnerId="voting"
      # - kubectl apply -f k8s-specifications/namespace.yaml

      - sed -i "s/{{tag}}/$CODEBUILD_RESOLVED_SOURCE_VERSION/g" k8s-specifications/vote-deployment.yaml
      - sed -i "s/{{tag}}/$CODEBUILD_RESOLVED_SOURCE_VERSION/g" k8s-specifications/worker-deployment.yaml
      - sed -i "s/{{tag}}/$CODEBUILD_RESOLVED_SOURCE_VERSION/g" k8s-specifications/result-deployment.yaml

      - kubectl apply -f k8s-specifications/
