version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t votingapp_vote vote
      - docker build -t votingapp_worker worker
      - docker build -t votingapp_result result
      - docker tag votingapp_vote $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_vote:$CODEBUILD_SOURCE_VERSION
      - docker tag votingapp_worker $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_worker:$CODEBUILD_SOURCE_VERSION
      - docker tag votingapp_result $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_result:$CODEBUILD_SOURCE_VERSION
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_vote:$CODEBUILD_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_worker:$CODEBUILD_SOURCE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/votingapp_result:$CODEBUILD_SOURCE_VERSION
