apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 417732881703.dkr.ecr.eu-west-1.amazonaws.com/votingapp_result:{{tag}}
        name: result
        imagePullPolicy: Always
      imagePullSecrets:
      - name: aws-registry
